export const IMPLEMENTATION_GUIDES = {
  "eu-ai-act": {
    intro: "Use this discovery guide to assess a client organisation's current state of compliance with the EU AI Act. Work through each area with the relevant stakeholder — Legal, Product, Engineering, or Risk — and capture current state, evidence, and gaps.",
    complianceDeadlines: [
      { date: "Aug 2025", requirement: "Prohibitions on unacceptable-risk AI active" },
      { date: "Aug 2025", requirement: "GPAI model obligations apply" },
      { date: "Aug 2026", requirement: "High-risk AI system obligations fully apply" },
      { date: "Aug 2027", requirement: "All remaining provisions" },
    ],
    areas: [
      {
        area: "AI System Inventory & Risk Classification",
        phaseGroup: "Govern & Scope",
        regulatoryRef: "Art. 6–9, Annex III — Risk Classification",
        dependencies: [],
        priority: "High",
        effort: "Medium",
        riskIfNotAddressed: "Non-compliance with foundational obligations; inability to demonstrate regulatory readiness; first target of supervisory authority review.",
        pillar: "governance",
        stakeholder: "CTO / Head of Product / Legal",
        questions: [
          "Do you have a complete inventory of all AI systems currently in use or development?",
          "For each system, has a risk classification been assigned (Unacceptable / High / Limited / Minimal)?",
          "Is there a documented process for classifying new AI systems before development begins?",
          "Who is accountable for maintaining the AI system register and keeping classifications current?",
        ],
        questionDeps: { 1: 0 }, // Q2 depends on Q1 — unlock when Q1 has any entry
        evidenceToCollect: ["AI system inventory spreadsheet or register", "Risk classification methodology document", "RACI for AI governance"],
        maturityIndicators: { notStarted: "No inventory exists. AI use cases are not tracked centrally.", developing: "Inventory exists but incomplete. No formal risk classification applied.", defined: "Complete inventory. Risk classification applied. Owner designated.", optimised: "Register is live, audited quarterly, integrated with change management." },
      },
      {
        area: "Prohibited AI Uses — Identification & Cessation",
        phaseGroup: "Govern & Scope",
        regulatoryRef: "Art. 5 — Prohibited Practices",
        dependencies: [],
        priority: "High",
        effort: "Low",
        riskIfNotAddressed: "Fines up to €35M or 7% of global turnover; criminal liability; immediate market withdrawal if prohibited use confirmed.",
        pillar: "ethics",
        stakeholder: "Legal / CISO / CTO",
        questions: [
          "Has the organisation reviewed all current AI use cases against Article 5 prohibited practices?",
          "Are any AI systems using real-time remote biometric identification in public spaces?",
          "Are any AI systems used for social scoring, manipulation of vulnerable groups, or subliminal influence?",
          "Is there a legal review process before any new biometric or emotion recognition AI is deployed?",
        ],
        evidenceToCollect: ["Legal review of current AI use cases against Article 5", "Written confirmation from business owners of no prohibited use", "Policy prohibiting future deployment without legal sign-off"],
        maturityIndicators: { notStarted: "No review of current AI against prohibitions has taken place.", developing: "Review in progress. Some use cases flagged for further analysis.", defined: "Full review completed. No prohibited uses confirmed in writing.", optimised: "Ongoing pre-deployment screening process in place. Legal sign-off required." },
      },
      {
        area: "High-Risk AI — Conformity Assessment",
        phaseGroup: "Map & Discover",
        regulatoryRef: "Art. 43, Annex IV — Conformity Assessment",
        dependencies: ["AI System Inventory & Risk Classification"],
        priority: "High",
        effort: "High",
        riskIfNotAddressed: "Cannot legally place high-risk AI systems on the EU market; regulatory enforcement action and mandatory product withdrawal.",
        pillar: "risk",
        stakeholder: "Product / Legal / Engineering",
        questions: [
          "Which AI systems fall into Annex III high-risk categories (employment, education, credit, law enforcement, health)?",
          "Has a conformity assessment been completed or planned for each high-risk AI system?",
          "Is there technical documentation covering system design, training data, testing, and performance?",
          "Has the system been registered in the EU AI Act database (required before market placement)?",
        ],
        evidenceToCollect: ["Conformity assessment reports", "Technical documentation packages", "EU AI database registration confirmations", "CE marking (where applicable)"],
        maturityIndicators: { notStarted: "High-risk systems not identified. No conformity assessment underway.", developing: "High-risk systems identified. Assessments planned but not started.", defined: "Conformity assessments completed for all high-risk systems.", optimised: "Assessments completed, registered, and reviewed on every significant change." },
      },
      {
        area: "Training Data Governance & Bias Examination",
        phaseGroup: "Map & Discover",
        regulatoryRef: "Art. 10 — Data & Data Governance",
        dependencies: ["AI System Inventory & Risk Classification"],
        priority: "High",
        effort: "High",
        riskIfNotAddressed: "Discriminatory AI outputs at scale; enforcement action; discrimination litigation; severe reputational and brand damage.",
        pillar: "privacy",
        stakeholder: "Data Engineering / ML / Legal / DPO",
        questions: [
          "Are training, validation, and test datasets documented with source, lineage, and collection date?",
          "Has a bias examination been conducted on datasets used for high-risk AI systems?",
          "Are gender, ethnicity, age, and other protected characteristics assessed for representativeness in training data?",
          "Is there a process for detecting and correcting data quality issues before training begins?",
        ],
        evidenceToCollect: ["Data lineage documentation", "Bias examination reports", "Dataset cards or datasheets for datasets", "Data quality assessment outputs"],
        maturityIndicators: { notStarted: "Training data is not documented. No bias examination has occurred.", developing: "Some datasets documented. Bias examination planned for priority systems.", defined: "All high-risk AI datasets documented and bias-examined.", optimised: "Automated dataset auditing in CI/CD pipeline. Bias reports version-controlled." },
      },
      {
        area: "Human Oversight & Override Controls",
        phaseGroup: "Map & Discover",
        regulatoryRef: "Art. 14 — Human Oversight",
        dependencies: ["High-Risk AI — Conformity Assessment"],
        priority: "Medium",
        effort: "Medium",
        riskIfNotAddressed: "Automated AI decisions deemed non-compliant; liability for harms caused by unmonitored outputs without human intervention.",
        pillar: "governance",
        stakeholder: "Product / Engineering / Operations",
        questions: [
          "Do high-risk AI systems allow a human operator to monitor, intervene, and override AI outputs?",
          "Are override actions logged with timestamp, operator ID, and reason?",
          "Are operators trained on when and how to exercise oversight?",
          "Is there a process for escalating AI decisions that require human review before action is taken?",
        ],
        evidenceToCollect: ["UI/system documentation showing override controls", "Audit log samples", "Operator training records", "Escalation procedures"],
        maturityIndicators: { notStarted: "AI outputs are fully automated. No override capability.", developing: "Override capability exists but not consistently implemented or logged.", defined: "Override controls on all high-risk AI. Logging and training in place.", optimised: "Override patterns reviewed monthly. Escalation triggers automated alerts." },
      },
      {
        area: "Fundamental Rights Impact Assessment",
        phaseGroup: "Map & Discover",
        regulatoryRef: "Art. 27 — FRIA",
        dependencies: ["AI System Inventory & Risk Classification"],
        priority: "High",
        effort: "Medium",
        riskIfNotAddressed: "Deployment of AI that violates fundamental rights; supervisory authority enforcement; public interest litigation and reputational harm.",
        pillar: "ethics",
        stakeholder: "Legal / DPO / Ethics Lead / Product",
        questions: [
          "Has a Fundamental Rights Impact Assessment (FRIA) been conducted for each high-risk AI deployment?",
          "Does the FRIA explicitly cover impacts on gender, ethnicity, disability, age, and intersectional groups?",
          "Is the FRIA completed before deployment, not after?",
          "Who signs off the FRIA and what authority do they have to halt deployment if risks are unacceptable?",
        ],
        evidenceToCollect: ["Completed FRIA documents", "Sign-off records", "Evidence of FRIA informing deployment decisions"],
        maturityIndicators: { notStarted: "No FRIA process exists.", developing: "FRIA template created. One or two assessments completed.", defined: "FRIA mandatory before all high-risk AI deployments. Results documented.", optimised: "FRIA integrated into product development gate. Published where required." },
      },
    ],
  },
  "nist-ai-rmf": {
    intro: "Use this guide to assess a client's implementation of the NIST AI Risk Management Framework across all four core functions: Govern, Map, Measure, Manage. Suitable for US-regulated organisations and multinationals adopting the RMF as a baseline.",
    complianceDeadlines: [
      { date: "Ongoing", requirement: "Voluntary framework — no mandatory deadlines. Sector-specific regulators (OCC, SEC, HHS) increasingly reference it." },
      { date: "2024", requirement: "NIST AI 600-1 (GenAI guidance) — assess all generative AI systems against additional risks." },
    ],
    areas: [
      {
        area: "GOVERN — AI Risk Policy & Accountability",
        regulatoryRef: "GOVERN 1.1–6.2 — Risk Culture & Policies",
        dependencies: [],
        priority: "High",
        effort: "Low",
        riskIfNotAddressed: "AI risks are ungoverned and invisible until an incident occurs; no named accountability for outcomes across the organisation.",
        pillar: "governance",
        stakeholder: "Board / CRO / General Counsel",
        questions: [
          "Is there a board-approved AI risk policy that defines the organisation's approach, risk appetite, and accountability?",
          "Is a named executive accountable for AI risk management (e.g. Chief AI Officer, Chief Risk Officer)?",
          "Are AI risk roles and responsibilities documented and communicated across the organisation?",
          "Is AI risk reviewed at board or senior management level on a regular schedule?",
        ],
        evidenceToCollect: ["AI risk policy document", "Board minute approving policy", "RACI or role definitions", "Board/committee AI risk reporting pack"],
        maturityIndicators: { notStarted: "No AI risk policy. AI risk not discussed at board level.", developing: "Draft policy exists. Ownership unclear. No board reporting.", defined: "Policy approved. Owner designated. Quarterly board reporting.", optimised: "Policy reviewed annually. AI risk is a standing board agenda item." },
      },
      {
        area: "MAP — Identifying Affected Populations & Risks",
        regulatoryRef: "MAP 1.1–5.2 — Risk Context & Classification",
        dependencies: ["GOVERN — AI Risk Policy & Accountability"],
        priority: "High",
        effort: "Medium",
        riskIfNotAddressed: "Harms to vulnerable groups go undetected; regulatory scrutiny from sector regulators; legal and reputational exposure.",
        pillar: "ethics",
        stakeholder: "Product / Data Science / Risk",
        questions: [
          "For each AI system, has the organisation documented who will be affected by its outputs (including indirectly)?",
          "Have vulnerable or marginalised groups who may be disproportionately impacted been explicitly identified?",
          "Is there a process to assess AI risks across societal, technical, and operational dimensions?",
          "Are bias and fairness risks included as formal risk categories in the AI risk register?",
        ],
        evidenceToCollect: ["Stakeholder and affected population maps", "AI risk register showing bias/fairness risk categories", "Pre-deployment risk assessments"],
        maturityIndicators: { notStarted: "No mapping of AI risks or affected populations.", developing: "Some systems have impact assessments. Not consistent.", defined: "All material AI systems mapped. Bias risk formally registered.", optimised: "Continuous impact monitoring. Feedback loops with affected communities." },
      },
      {
        area: "MEASURE — Fairness Metrics & Monitoring",
        regulatoryRef: "MEASURE 1.1–4.2 — Metrics & Testing",
        dependencies: ["MAP — Identifying Affected Populations & Risks"],
        priority: "Medium",
        effort: "High",
        riskIfNotAddressed: "Bias and fairness issues in production go undetected; discriminatory outcomes affect customers at scale before discovered.",
        pillar: "ethics",
        stakeholder: "ML Engineering / Data Science / Product",
        questions: [
          "Are fairness metrics (demographic parity, equalised odds, calibration) defined and measured for AI systems?",
          "Are model performance results disaggregated by gender, age, ethnicity, and other protected characteristics?",
          "Is there a baseline established pre-deployment that ongoing production metrics are compared against?",
          "Are measurement results reviewed by a person with authority to intervene if thresholds are breached?",
        ],
        evidenceToCollect: ["Fairness metric definitions", "Model cards or evaluation reports", "Disaggregated performance dashboards", "Threshold breach records and responses"],
        maturityIndicators: { notStarted: "No fairness metrics defined or measured.", developing: "Metrics defined for some systems. Not consistently monitored.", defined: "Metrics defined, baselined, and monitored for all material systems.", optimised: "Automated alerts on threshold breach. Metrics trend-tracked over model versions." },
      },
      {
        area: "MANAGE — Risk Treatment & Incident Response",
        regulatoryRef: "MANAGE 1.1–4.2 — Risk Response & Recovery",
        dependencies: ["GOVERN — AI Risk Policy & Accountability"],
        priority: "High",
        effort: "Medium",
        riskIfNotAddressed: "No ability to contain or respond to AI incidents; extended exposure window; regulatory breach notification failures.",
        pillar: "risk",
        stakeholder: "CRO / CISO / Product / Legal",
        questions: [
          "Is there a documented process for treating AI risks — covering mitigation, transfer, acceptance, and avoidance?",
          "Is there a defined AI incident response playbook covering bias events, model failures, and harmful outputs?",
          "Has the incident response playbook been tested via a tabletop exercise in the last 12 months?",
          "Are AI-related incidents logged, investigated, root-caused, and tracked to resolution?",
        ],
        evidenceToCollect: ["AI risk treatment plans", "AI incident response playbook", "Tabletop exercise records", "AI incident log"],
        maturityIndicators: { notStarted: "No AI-specific risk treatment or incident process.", developing: "Risk treatment ad-hoc. No AI incident playbook.", defined: "Treatment plans documented. Playbook exists and tested.", optimised: "Incident metrics reviewed monthly. Playbook updated after each incident." },
      },
    ],
  },
  "nist-csf": {
    intro: "Use this guide to assess a client's implementation of NIST CSF 2.0 with specific focus on AI and ML system security controls, supply chain risk, and the new GOVERN function.",
    complianceDeadlines: [
      { date: "Ongoing", requirement: "Voluntary framework. CISA and sector regulators increasingly mandate CSF alignment." },
      { date: "2024", requirement: "CSF 2.0 released — clients on v1.1 should plan migration including new GOVERN function." },
    ],
    areas: [
      {
        area: "GOVERN — AI Security Policy & Risk Strategy",
        regulatoryRef: "GV.OC, GV.RM — Organisational Context & Risk Mgmt",
        dependencies: [],
        priority: "High",
        effort: "Low",
        riskIfNotAddressed: "AI security risks ungoverned; no accountability for security outcomes; significant blind spots in threat landscape.",
        pillar: "governance",
        stakeholder: "CISO / CRO / Board",
        questions: [
          "Has the organisation updated its cybersecurity risk strategy to explicitly include AI and ML systems?",
          "Is there a defined risk tolerance for AI-specific threats (adversarial attacks, model poisoning, prompt injection)?",
          "Are AI systems included in the organisation's enterprise risk register?",
          "Who owns AI cybersecurity risk — and how does that role interact with the AI governance function?",
        ],
        evidenceToCollect: ["Updated risk strategy document", "Enterprise risk register showing AI risks", "AI-specific risk tolerance statements"],
        maturityIndicators: { notStarted: "AI security risks not in scope of cybersecurity strategy.", developing: "AI risks informally considered. Not in formal risk strategy.", defined: "AI risks in risk strategy with defined tolerance. Owner designated.", optimised: "AI security risk reviewed quarterly at board level alongside cyber risk." },
      },
      {
        area: "AI Asset Inventory & Supply Chain",
        regulatoryRef: "ID.AM, ID.SC — Asset & Supply Chain",
        dependencies: ["GOVERN — AI Security Policy & Risk Strategy"],
        priority: "High",
        effort: "Medium",
        riskIfNotAddressed: "Unknown AI attack surface; third-party components introduce unmanaged risk; supply chain compromise goes undetected.",
        pillar: "governance",
        stakeholder: "CISO / Procurement / CTO",
        questions: [
          "Are AI models, training datasets, and inference endpoints included in the organisation's asset inventory (CMDB)?",
          "Are third-party AI model providers and data vendors assessed for security risk before onboarding?",
          "Is there an AI-specific vendor risk questionnaire covering bias, security, and data governance?",
          "Are vendor AI security attestations reviewed annually?",
        ],
        evidenceToCollect: ["CMDB extract showing AI assets", "Vendor risk assessment templates", "AI supplier contracts with security clauses"],
        maturityIndicators: { notStarted: "No AI assets in CMDB. No vendor AI risk process.", developing: "Some AI assets tracked. Vendor process under development.", defined: "CMDB includes AI assets. Vendor AI questionnaire in use.", optimised: "Continuous asset discovery. Annual vendor attestations with right-to-audit." },
      },
      {
        area: "Training Data & Model Security",
        regulatoryRef: "PR.DS, PR.AT — Data Security & Awareness",
        dependencies: ["AI Asset Inventory & Supply Chain"],
        priority: "High",
        effort: "High",
        riskIfNotAddressed: "Model theft, poisoning, or data exfiltration; AI systems produce compromised outputs without detection or alerting.",
        pillar: "privacy",
        stakeholder: "CISO / Data Engineering / ML",
        questions: [
          "Are training datasets encrypted at rest and in transit with access controls and audit logging?",
          "Is gender or other sensitive demographic data in training corpora classified as sensitive and access-restricted?",
          "Are AI model weights and artefacts protected with the same rigour as source code?",
          "Is there a process to detect and respond to training data tampering or model poisoning?",
        ],
        evidenceToCollect: ["Data classification policy", "Encryption standards documentation", "Access control configurations", "Anomaly detection runbooks"],
        maturityIndicators: { notStarted: "Training data treated as generic data. No specific controls.", developing: "Encryption applied. Access controls inconsistent.", defined: "Training data classified. Encryption, access controls, and audit logging in place.", optimised: "Automated integrity checks on training data. Tampering triggers incident." },
      },
      {
        area: "AI Incident Detection & Response",
        regulatoryRef: "DE.CM, RS.CO — Detect & Respond",
        dependencies: ["GOVERN — AI Security Policy & Risk Strategy"],
        priority: "Medium",
        effort: "Medium",
        riskIfNotAddressed: "AI security incidents go undetected or are poorly contained; mandatory breach notification obligations breached.",
        pillar: "risk",
        stakeholder: "CISO / SOC / Legal",
        questions: [
          "Is there an AI-specific anomaly detection capability covering adversarial inputs and biased output patterns?",
          "Are AI systems included in the Security Operations Centre (SOC) monitoring scope?",
          "Is there a defined notification process for AI-related incidents affecting customers or regulators?",
          "Does the disaster recovery plan include AI model rollback and fairness re-validation procedures?",
        ],
        evidenceToCollect: ["SOC monitoring scope documentation", "AI anomaly detection playbooks", "Incident notification templates", "DR plan AI section"],
        maturityIndicators: { notStarted: "AI not in SOC scope. No AI incident playbook.", developing: "AI in scope but limited detection rules. Playbook drafted.", defined: "AI-specific detection and playbook. Notification process defined.", optimised: "AI incidents auto-escalated. Recovery tested annually including rollback." },
      },
    ],
  },
  "iso-42001": {
    intro: "Use this guide to assess a client's readiness for ISO 42001 certification or to identify gaps in their AI Management System (AIMS). Map findings to the clause structure for use in a formal gap assessment.",
    complianceDeadlines: [
      { date: "2023", requirement: "Standard published. Certification available from accredited bodies." },
      { date: "Ongoing", requirement: "No mandatory deadline — client-driven. Some procurement and regulatory bodies beginning to require it." },
    ],
    areas: [
      {
        area: "Clause 4–5: Context, Leadership & AI Policy",
        regulatoryRef: "ISO 42001 Clauses 4–5 — Context & Leadership",
        dependencies: [],
        priority: "High",
        effort: "Low",
        riskIfNotAddressed: "ISO 42001 certification unachievable without leadership clause; no executive accountability for AI management system.",
        pillar: "governance",
        stakeholder: "CEO / Board / General Counsel",
        questions: [
          "Has the organisation documented the internal and external issues relevant to its AI management system?",
          "Is there a board-approved AI policy that commits to responsible AI, legal compliance, and continual improvement?",
          "Does the AI policy explicitly address fairness, non-discrimination, and gender equity in AI outcomes?",
          "Has top management assigned roles and responsibilities for the AI management system?",
        ],
        evidenceToCollect: ["Context analysis document", "Board-approved AI policy", "Role and responsibility matrix"],
        maturityIndicators: { notStarted: "No AI policy. Context not documented.", developing: "Draft policy. Context analysis incomplete.", defined: "Policy approved. Context documented. Roles assigned.", optimised: "Policy reviewed annually. Context analysis feeds risk assessment." },
      },
      {
        area: "Clause 6: AI Risk Assessment & Planning",
        regulatoryRef: "ISO 42001 Clause 6 — Planning",
        dependencies: ["Clause 4–5: Context, Leadership & AI Policy"],
        priority: "High",
        effort: "Medium",
        riskIfNotAddressed: "AI risks discovered reactively; no systematic treatment planning; major nonconformity at certification audit.",
        pillar: "risk",
        stakeholder: "Risk / Product / Legal",
        questions: [
          "Is there a documented methodology for identifying, analysing, and evaluating AI risks?",
          "Are AI risks assessed across the full lifecycle — design, development, deployment, and decommissioning?",
          "Is bias risk formally assessed for each AI system using a documented methodology?",
          "Are the results of risk assessments used to determine what controls and treatments are needed?",
        ],
        evidenceToCollect: ["AI risk assessment methodology", "Completed risk assessments for in-scope systems", "Risk treatment plan"],
        maturityIndicators: { notStarted: "No AI risk assessment process.", developing: "Process defined but not consistently applied.", defined: "Methodology documented. Assessments completed for all in-scope systems.", optimised: "Assessments triggered automatically on significant change. Results feed board reporting." },
      },
      {
        area: "Clause 8: AI System Impact Assessment & Operation",
        regulatoryRef: "ISO 42001 Clause 8, Annex B — Operation & AIIA",
        dependencies: ["Clause 6: AI Risk Assessment & Planning"],
        priority: "High",
        effort: "High",
        riskIfNotAddressed: "AI impacts on people and society unassessed; ethical failures reach customers; ISO 42001 major nonconformity.",
        pillar: "ethics",
        stakeholder: "Product / Legal / DPO / Ethics Lead",
        questions: [
          "Is a pre-deployment AI impact assessment conducted for all in-scope AI systems?",
          "Does the impact assessment include disparate impact analysis across demographic groups (gender, ethnicity, age)?",
          "Are responsible AI use controls implemented — human oversight, data quality checks, transparency mechanisms?",
          "Who has authority to halt deployment if the impact assessment identifies unacceptable risks?",
        ],
        evidenceToCollect: ["Impact assessment templates and completed assessments", "Deployment gate approval records", "Evidence of human oversight controls"],
        maturityIndicators: { notStarted: "No impact assessment process.", developing: "Template created. One or two assessments done.", defined: "Mandatory pre-deployment. Disparate impact assessed. Gate approval required.", optimised: "Assessments automated where possible. Results tracked over model versions." },
      },
      {
        area: "Clause 9–10: Internal Audit & Continual Improvement",
        regulatoryRef: "ISO 42001 Clauses 9–10 — Performance & Improvement",
        dependencies: ["Clause 8: AI System Impact Assessment & Operation"],
        priority: "Medium",
        effort: "Medium",
        riskIfNotAddressed: "No evidence of AIMS performance; certification suspended or not renewed; unresolved nonconformities accumulate.",
        pillar: "risk",
        stakeholder: "Internal Audit / CRO / Board",
        questions: [
          "Is there an annual internal audit programme for the AI management system?",
          "Do internal audits cover fairness metrics, bias incidents, and data governance?",
          "Are audit findings tracked as nonconformities with root cause analysis and corrective action?",
          "Is the AI management system reviewed by top management at least annually?",
        ],
        evidenceToCollect: ["Internal audit plan and reports", "Nonconformity and corrective action register", "Management review minutes"],
        maturityIndicators: { notStarted: "No AI internal audit. No management review.", developing: "Audit planned. Management review ad-hoc.", defined: "Annual audit completed. Findings tracked. Management review documented.", optimised: "Audit insights drive continual improvement cycle. Metrics trend upward year-on-year." },
      },
    ],
  },
  "fair": {
    intro: "Use this guide to assess whether a client organisation has the capability to quantify AI risk in financial terms using the FAIR methodology. Most useful for financial services, insurance, and technology clients with mature risk management functions.",
    complianceDeadlines: [
      { date: "Ongoing", requirement: "Voluntary methodology. Increasingly referenced by financial regulators and insurance underwriters." },
    ],
    areas: [
      {
        area: "Risk Taxonomy & Scenario Identification",
        regulatoryRef: "FAIR Phase 1 — Scenario Identification",
        dependencies: [],
        priority: "High",
        effort: "Low",
        riskIfNotAddressed: "Quantification is impossible without agreed taxonomy; risk conversations are inconsistent and results incomparable across teams.",
        pillar: "risk",
        stakeholder: "CRO / Risk Analyst / CISO",
        questions: [
          "Has the organisation identified and documented AI-specific risk scenarios (model failure, data poisoning, bias at scale, adversarial attack)?",
          "Are AI risk scenarios mapped to the FAIR taxonomy — Loss Event Frequency and Loss Magnitude?",
          "Is gender discrimination / bias-related regulatory action included as a defined loss event scenario?",
          "Who owns AI risk scenario development and how often are scenarios reviewed?",
        ],
        evidenceToCollect: ["AI risk scenario library", "FAIR taxonomy mapping document", "Risk scenario review records"],
        maturityIndicators: { notStarted: "No AI risk scenarios defined.", developing: "Some scenarios identified. Not mapped to FAIR taxonomy.", defined: "Scenarios mapped to FAIR. Reviewed annually.", optimised: "Scenario library maintained. New scenarios added following industry events." },
      },
      {
        area: "Quantitative Risk Modelling",
        regulatoryRef: "FAIR Phase 2–3 — Risk Quantification",
        dependencies: ["Risk Taxonomy & Scenario Identification"],
        priority: "Medium",
        effort: "High",
        riskIfNotAddressed: "AI risks expressed qualitatively only; unable to prioritise investments or set cyber insurance levels by financial impact.",
        pillar: "risk",
        stakeholder: "Risk / Finance / CRO",
        questions: [
          "Is the organisation using Monte Carlo simulation to quantify AI risk exposure in dollar terms?",
          "Are EU AI Act and GDPR fine ranges incorporated into Secondary Loss Magnitude estimates?",
          "Is there a tooling platform in use (e.g. RiskLens, FAIR-U) or are models built in-house?",
          "Are FAIR risk model results presented to the board as financial exposure ranges, not heat map ratings?",
        ],
        evidenceToCollect: ["FAIR model outputs", "Board risk reports showing financial exposure", "Tooling platform access"],
        maturityIndicators: { notStarted: "Risk quantified only as High/Medium/Low ratings.", developing: "FAIR methodology known. Pilot model built for one scenario.", defined: "FAIR models for all material AI risks. Results in board pack.", optimised: "Models updated quarterly. Risk reduction ROI calculated for control investments." },
      },
      {
        area: "Threat & Vulnerability Analysis",
        regulatoryRef: "FAIR Phase 2 — Threat Analysis",
        dependencies: ["Risk Taxonomy & Scenario Identification"],
        priority: "Medium",
        effort: "Medium",
        riskIfNotAddressed: "Threat landscape not understood; risk models underestimate actual financial exposure; mispriced and underinsured risk.",
        pillar: "risk",
        stakeholder: "CISO / ML Engineering / Risk",
        questions: [
          "Have threat actors relevant to the organisation's AI systems been identified (adversarial, insider, vendor)?",
          "Is the vulnerability of AI systems to adversarial attacks assessed and scored?",
          "Are bias amplification and gender stereotype reinforcement modelled as exploitable vulnerabilities?",
          "Is there a red team or penetration testing function that covers AI-specific attack vectors?",
        ],
        evidenceToCollect: ["Threat actor profiles", "AI vulnerability assessments", "Red team / pen test reports covering AI"],
        maturityIndicators: { notStarted: "AI threat and vulnerability analysis not performed.", developing: "Threat actors identified. Vulnerability assessment ad-hoc.", defined: "Formal threat and vulnerability analysis. AI pen testing annual.", optimised: "Continuous threat intelligence. AI red team capability in-house." },
      },
    ],
  },
  "aaia": {
    intro: "Use this guide to structure an AI audit engagement or to assess a client's readiness for an AAIA-aligned AI audit. Work through each domain with the internal audit, risk, or compliance function.",
    complianceDeadlines: [
      { date: "Ongoing", requirement: "No mandatory timeline. Increasing regulatory and procurement demand for AI audit evidence." },
      { date: "2024", requirement: "CAAIA exam updated — ensure audit methodology aligns with EU AI Act conformity assessment." },
    ],
    areas: [
      {
        area: "Domain 1–2: Audit Charter & Risk-Based Planning",
        regulatoryRef: "AAIA Domains 1–2 — Audit Foundation",
        dependencies: [],
        priority: "High",
        effort: "Low",
        riskIfNotAddressed: "Internal audit has no mandate to assess AI; board has no independent assurance on AI risk; control failures go unreported.",
        pillar: "governance",
        stakeholder: "Chief Audit Executive / Audit Committee",
        questions: [
          "Does the internal audit charter explicitly include AI systems, algorithmic bias, and fairness in scope?",
          "Is there an annual AI audit plan that prioritises systems by risk level, regulatory exposure, and societal impact?",
          "Are AI systems affecting employment, credit, healthcare, and education audited for gender equity as a priority?",
          "Does the audit function have AI technical expertise — either in-house or through co-sourcing arrangements?",
        ],
        evidenceToCollect: ["Internal audit charter", "Annual AI audit plan", "Audit committee approval minutes", "AI competency matrix for audit team"],
        maturityIndicators: { notStarted: "AI not in audit charter. No AI audit plan.", developing: "Charter updated. AI audit plan in draft.", defined: "Charter and plan approved. Risk-based prioritisation applied.", optimised: "AI audit integrated with enterprise risk. CAAIA-certified auditors on team." },
      },
      {
        area: "Domain 3: Algorithmic Bias Testing",
        regulatoryRef: "AAIA Domain 3 — Algorithmic Bias Audit",
        dependencies: ["Domain 1–2: Audit Charter & Risk-Based Planning"],
        priority: "High",
        effort: "High",
        riskIfNotAddressed: "Biased AI decisions not caught by audit; discriminatory outcomes reach customers; audit function not fit for purpose in AI era.",
        pillar: "ethics",
        stakeholder: "Internal Audit / ML Engineering / Data Science",
        questions: [
          "Is a structured bias testing methodology applied to AI systems — covering disparate impact and disparate treatment?",
          "Are demographic parity, equalised odds, and calibration metrics measured and documented for audited systems?",
          "Is gender treated as a mandatory protected characteristic in all bias audit engagements?",
          "Is intersectional analysis conducted (e.g. gender × ethnicity, gender × age) where data permits?",
        ],
        evidenceToCollect: ["Bias testing methodology document", "Bias audit reports with metric outputs", "Evidence of gender and intersectional analysis"],
        maturityIndicators: { notStarted: "No bias testing performed.", developing: "Bias testing done for one or two systems. Methodology informal.", defined: "Structured methodology. All material systems tested. Gender mandatory.", optimised: "Automated bias testing in deployment pipeline. Results published to affected stakeholders." },
      },
      {
        area: "Domain 5: Training Data Quality Audit",
        regulatoryRef: "AAIA Domain 5 — Data Quality",
        dependencies: ["Domain 1–2: Audit Charter & Risk-Based Planning"],
        priority: "Medium",
        effort: "High",
        riskIfNotAddressed: "Data quality issues in AI training unidentified by audit; model performance and fairness compromised without audit evidence.",
        pillar: "privacy",
        stakeholder: "Internal Audit / Data Engineering / DPO",
        questions: [
          "Are training datasets audited for representativeness, accuracy, and freedom from historical bias?",
          "Is gender representation in training data measured and documented?",
          "Is historical underrepresentation of gender groups flagged as an audit finding requiring remediation?",
          "Is personal data in training datasets identified and subject to privacy controls?",
        ],
        evidenceToCollect: ["Data quality audit reports", "Dataset composition analysis", "Personal data inventory for training datasets"],
        maturityIndicators: { notStarted: "Training data quality not audited.", developing: "Data quality checks informal. Gender representation not measured.", defined: "Structured data audit. Gender representation documented. PII controlled.", optimised: "Automated data quality gates. Representation metrics tracked over time." },
      },
      {
        area: "Domain 6–7: Governance Audit & Reporting",
        regulatoryRef: "AAIA Domains 6–7 — Governance & Reporting",
        dependencies: ["Domain 1–2: Audit Charter & Risk-Based Planning"],
        priority: "Medium",
        effort: "Medium",
        riskIfNotAddressed: "AI governance failures unreported to board; inadequate oversight of AI risk programme; board-level accountability gaps persist.",
        pillar: "governance",
        stakeholder: "Internal Audit / Board / Risk Committee",
        questions: [
          "Does the governance audit assess whether bias incidents are escalated, investigated, and resolved systematically?",
          "Is the diversity of the AI governance committee assessed as a quality indicator?",
          "Are audit findings rated using a standardised severity scale with defined management response timelines?",
          "Are gender equity findings tracked separately with their own follow-up timeline and owner?",
        ],
        evidenceToCollect: ["Governance audit reports", "AI committee membership records", "Finding remediation tracker", "Audit committee reporting pack"],
        maturityIndicators: { notStarted: "No governance audit. Findings not formally tracked.", developing: "Governance reviewed informally. Tracking inconsistent.", defined: "Governance audit conducted. Findings rated and tracked to closure.", optimised: "Gender equity findings tracked separately. Audit committee reviews trend data." },
      },
    ],
  },
};
